### ISSUE TITLE
README.md not being detected, despite being present

### ISSUE THREAD

**Issue by aspidites** [purescript/pursuit#154]
![2015-10-19-070115_731x158_scrot](https://cloud.githubusercontent.com/assets/93686/10576165/3b3a7876-762f-11e5-879d-3c3d8eefa544.png)
[Halogen 0.5.1](http://pursuit.purescript.org/packages/purescript-halogen/0.5.1) was recently released, but the pursuit page for it says that no README could be found, despite there being one prominently placed in the github repo. I attempted to regenerate the documentation for it (hence why it says that I am the uploader, even though it was there before hand). I saw that other packages seemed to be having issues, but upon a quick glance (pardon if I missed something, it's rather early in the morning here), I didn't see any obvious fixes.

**Comment by tfausak** [comment]
:+1: I have yet to find a package with a README on Pursuit.

**Comment by paf31** [comment]
They used to be there but have disappeared. I'm not so familiar with this part of the code, so I'll need to spend some time figuring this out. It might be related to GitHub's rate limits.

**Comment by tfausak** [comment]
It looks like [tryGetReadme](https://github.com/purescript/pursuit/blob/aad2298a09c70ff2b4c0f0c3f9f5da103cee5ce9/src/TemplateHelpers.hs#L48-L59) logs any errors that happen.

**Comment by paf31** [comment]
Yes, it's rate limiting. I'd personally be fine with just a link to the readme file on GitHub, and a package description from `bower.json`. Any thoughts?

**Comment by garyb** [comment]
Why do we read it from GitHub rather than just taking a local readme in `psc-publish` and integrating that into the uploaded info? The pursuit.md proposal #150 seems relevant too.

**Comment by tfausak** [comment]
I was about to say the same thing, @garyb. :+1:

**Comment by paf31** [comment]
I don't remember why we don't do that but it seems sensible. Linking to a GitHub tag of the README file seems just as good to me, and would unclutter things a bit too.

**Comment by paf31** [comment]
I also like the idea of `pursuit.md`.

**Comment by tfausak** [comment]
I would prefer using the local `README.md` over both linking to GitHub and using `PURSUIT.md`. I like keeping all of the information in one place. For Haskell packages, the split between `README.md` and the `description` field in `package.cabal` drives me nuts. I like how Stackage and now Hackage show the READMEs on the package pages.

**Comment by hdgarrood** [comment]
If readmes are not showing up that might indicate that the caching is
broken. Pursuit should only have to fetch any given readme once. What do
the pages in the cache look like?

Also is Pursuit using authentication to get the higher rate limit? I think it should be.

The reason I decided to use github originally instead of putting the
readme into the json blob was that seemed the best way of avoiding
rendering issues. We want it to look the same as it does on github, and
there are a few differences between github's renderer and any open
source ones. Also, doing it this way means that it works for people who
use anything other than markdown.

**Comment by hdgarrood** [comment]
@paf31 what design were you thinking for `pursuit.md`? I don't think there's a consensus yet on #150.

**Comment by paf31** [comment]
@hdgarrood Well if the file exists, we could bundle it into the output of `psc-publish`, and render it using `cheapskate` on the server. If not, we could fall back to `readme.md`, but I'd be in favour of deprecating that option and just adding a warning to newer versions of `psc-publish`.

**Comment by hdgarrood** [comment]
Ok, that sounds good to me. I'd be fine with rendering `pursuit.md` using Cheapskate, it's just readmes I can see that potentially causing problems with.

The only thing I want to clear up is what we'd expect the differences between the readme and `pursuit.md` to be; what we'd expect people to put in each one, and what we'd do in all the core packages. Were you thinking `pursuit.md` would generally be the same as the readme except that it wouldn't have the "Module documentation" section?

Also, come to think of it, I'm not such a fan of the name `pursuit.md`. I think I'd rather `documentation.md` or maybe just `docs.md`.

**Comment by hdgarrood** [comment]
@paf31 and I just went on the server and fixed the issue - we've provided a github api access token which pursuit uses for all of the github api calls, and this increases the rate limit by quite a lot. We also fixed the configuration so that the caching actually works. With both of these things now working I doubt we'll see this problem again. :)

**Comment by tfausak** [comment]
Looks great, thanks!
