### ISSUE TITLE
Type class members and instances aren't documented

### ISSUE THREAD

**Issue by tfausak** [purescript/pursuit#159]
The documentation for type class members isn't being generated. For example, I document the `add` member of `HasAdd`, but it doesn't show up on Pursuit.

http://pursuit.purescript.org/packages/purescript-neon/0.0.26/docs/Neon.Types.HasAdd#t:HasAdd
https://github.com/tfausak/purescript-neon/blob/v0.0.26/src/Neon/Types/HasAdd.purs#L19-L25

**Comment by hdgarrood** [comment]
I can't remember whether this was originally by design or just didn't seem worth implementing, but looking at it now I think I agree that it should be possible to document type class members in this way.

**Comment by nicholaskariniemi** [comment]
Showing documentation for class instances would also be awesome. I'm just learning that there is a wealth of information in instance documentation like this for [Either](https://github.com/purescript/purescript-either/blob/v0.2.3/src/Data/Either.purs#L52-L236).

**Comment by hdgarrood** [comment]
I'm not so sure about instances. I think instances are usually better documented on the data type itself.

**Comment by tfausak** [comment]
I disagree. I think documenting instances is also very useful. Especially considering you can define instances separate from the data type, which means they could never be documented. For example, how would you document `Maybe`'s `Foldable` instance given that it's defined in `Data.Foldable` instead of `Data.Maybe`?

**Comment by hdgarrood** [comment]
I did say "usually". `Foldable Maybe` is a good counterexample. But in the case where the module where the type is defined knows nothing about the class, you could document the instance on the class.

As we have it currently, I think the instance list is fantastic for skimming over when you already know what most/all of these types and type classes do, and I don't want to lose that. Documentation should of course be useful for newcomers, but we mustn't forget that it's also used by experienced users who just need to look something up because they can't quite remember how it works.

I think `purescript-aff` is a great example of how it should be done, for instance. I can read the README if I'm a new user, or if not, I can look in the docs, see `MonadError Error (Aff e)` and instantly know what that means.

Maybe we could start including instance documentation, but have it collapsed by default, and expandable using a [+] button.

**Comment by paf31** [comment]
I think `Foldable` is a particularly bad case because of its lack of laws, it becomes harder to infer what an instance does from a) the class and its docs, and b) the data type and its docs. But in general, I think we should be associating type classes with collections of operations and laws (documented with the class), so either the implementation is unimportant, since the laws are all that matter, or if the implementation is important, it should be documented on the type.

**Comment by tfausak** [comment]
What about stuff like Servant's `HasServer` class? 
http://hackage.haskell.org/package/servant-server-0.4.4.6/docs/Servant-Server.html#g:3

**Comment by hdgarrood** [comment]
Yeah, that's another good example of where you'd want docs on individual instances, I guess. But I think the type-level programming capabilities we have in PureScript right now mean that stuff like Servant isn't going to be possible for a while.

**Comment by tfausak** [comment]
I still want to be able to document members and instances. Even with lawful type classes, it can help to document tricky instances. Consider [the function instance for monads](http://haddock.stackage.org/lts-5.15/base-4.8.2.0/Prelude.html#t:Monad). Even if you fully grok the laws it can be hard to wrap your head around how they apply to functions.

**Comment by hdgarrood** [comment]
Yeah, ok, you've persuaded me. I think it would be good to allow documentation of instances for cases like the ones you've given. I think we could make the UI similar to what Hackage does (although I would still prefer them to not be visible by default, I think).

**Comment by tfausak** [comment]
I'm glad I persuaded you! 

I would prefer to have them visible by default, but that's probably not surprising. I'm also not a huge fan of how Hackage does it. The instances themselves can get pretty wide, and then they add a bunch of text to the side. They probably did that so you can still scan the left column for instances, but there's got to be a better way. Maybe a [description list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl)? 

``` html
<h3>Instances</h3>
<dl>
  <dt><code>Monad []</code></dt>
  <dd><!-- no documentation for this one --></dd>

  <dt><code>Monad ((->) r)</code></dt>
  <dd>blah blah blah</dd>
```

**Comment by hdgarrood** [comment]
Oh yeah, I meant like Hackage except with more sensible wrapping ;) That HTML looks sensible to me (although I think we ought to be able to make it work with a `<ul>` too, as we do currently). I'm more interested in how it looks on the page, though.

**Comment by tfausak** [comment]
I like `<dl>` for its semantics, but you can accomplish the same thing with a `<ul>` and some CSS. 

The default styling for `<dl>` is pretty close to how I would want this to look. Here's a JS Bin example: http://jsbin.com/satodikupe/edit?html,output

**Comment by tfausak** [comment]
I don't think #244 actually fixes this issue. It allows you to search for type class members (like `Functor`'s `map`), but it doesn't allow you to document those members.

**Comment by paf31** [comment]
Yes, good point, thanks.

**Comment by donabrams** [comment]
A good use case for this:

Searched for `(a -> Maybe b) -> m a -> m b` and it didn't find `filterMap`

**Comment by hdgarrood** [comment]
That's a separate issue, what's being discussed here doesn't affect search results. We are considering using the same mechanism that drives typed hole suggestions in the compiler to give better type search results; i can't remember if there's an issue for that already.
