### ISSUE TITLE
Badges aren't being updated

### ISSUE THREAD

**Issue by zudov** [purescript/pursuit#162]
For example http://pursuit.purescript.org/packages/purescript-strongcheck-generics/badge/ says `0.2.0` while it should be `0.2.1` (updated about a day ago).

Another example is http://pursuit.purescript.org/packages/purescript-websocket-simple/badge which is 404 even though the package is present (I've uploaded it a few minutes ago).

I guess there is a cache in front of badge endpoint, perhaps it should be adjusted.
I guess 404 appeared because I've made a few requests to `purescript-websocket-simple`'s badge endpoint *before* I published it, so 404 got cached.

**Comment by hdgarrood** [comment]
I know why the out of date badge is happening: I forgot to clear the cached badge when new package versions are uploaded.

The 404 is weird. That might be because of the change in #160? @paf31 could you check what happens if you request `GET /packages/purescript-websocket-simple/badge` directly to the Yesod server without going via nginx?

**Comment by paf31** [comment]
`v0.0.1`

**Comment by hdgarrood** [comment]
And now it appears to be working from here, presumably because the SVG has been written to disk and it's being served directly by nginx from the disk. I am becoming more convinced that the problem is in the nginx configuration. If you delete the cache for that badge, and then request the same badge again from outside (ie through nginx), can you check if the request reaches the Yesod server?

**Comment by paf31** [comment]
The server only has `0.0.1.json`. Removing the cache and `curl`ing again still gives the badge for `0.0.1`.

**Comment by paf31** [comment]
Also `index.html` wasn't getting updated, and I had to delete it to show the new items on the front page. Not sure if that's Nginx or Yesod though.

**Comment by hdgarrood** [comment]
oh as in the root of the whole site isn't getting updated? Oh yeah, that may well be another one I forgot to clear.

Um, if requesting via nginx after deleting the cache is working now then I don't know what was going on. I would have thought that would put us back in the original state where we were getting 404s.

**Comment by hdgarrood** [comment]
Closing for now as the stale badge issue has been resolved and we're unable to reproduce the 404 issue. If it happens again then I'll have another look.

**Comment by zudov** [comment]
http://pursuit.purescript.org/packages/purescript-strongcheck-generics/badge/ is still `v0.2.0`, even though the latest one is `v0.3.0`. Would new release force the update?

**Comment by hdgarrood** [comment]
The fix is in master but it hasn't been deployed yet.

**Comment by zudov** [comment]
@hdgarrood Ok. Thanks!
