### ISSUE TITLE
A link to the docs for the latest version?

### ISSUE THREAD

**Issue by sharkdp** [purescript/pursuit#169]
I would like to link to the Pursuit documentation from the Github README.md, because it is much nicer than just the Markdown files. Is it possible to link to the latest version of the docs for a specific module?

Something like
`http://pursuit.purescript.org/packages/purescript-flare/`**`latest`**`/docs/Flare`

instead of
`http://pursuit.purescript.org/packages/purescript-flare/0.1.7/docs/Flare`

In general, what is the proposed way to do this? It's kind of strange that Pursuit includes the Github README which often refers to the Markdown docs in the repository... I often find myself clicking these links on Pursuit, taking me back to Github.

**Comment by hdgarrood** [comment]
Yes, there is: just http://pursuit.purescript.org/packages/purescript-flare/ which will redirect to the latest version. There's no way to link to a specific module at a specific version at the moment, though.

**Comment by hdgarrood** [comment]
And I agree that the current situation is a bit strange. I want to eventually get rid of all links to markdown documentation, and maybe even get rid of checked in markdown documentation entirely; Pursuit should be the place for documentation, I think. But I want to improve the UX around publishing packages to pursuit first. Lots of libraries only have one or two versions there, because it's admittedly rather awkward at the moment. See for example bodil/pulp#57 (which I want to address after the purescript port is done).

**Comment by sharkdp** [comment]
> There's no way to link to a specific module at a specific version at the moment, though.

Ok, I think it's not too important. I'll probably just link to the overview page, thanks.

> I want to eventually get rid of all links to markdown documentation, and maybe even get rid of checked in markdown documentation entirely; Pursuit should be the place for documentation, I think.

Completely agree. :+1: 

> But I want to improve the UX around publishing packages to pursuit first. Lots of libraries only have one or two versions there, because it's admittedly rather awkward at the moment. See for example bodil/pulp#57 (which I want to address after the purescript port is done).

That's a good idea, thanks!

**Comment by fiatjaf** [comment]
Any news on this?

I would highly appreciate something like redirecting from `https://pursuit.purescript.org/packages/purescript-aff/latest/docs/Control.Monad.Aff.Class`
to 
`https://pursuit.purescript.org/packages/purescript-aff/2.0.3/docs/Control.Monad.Aff.Class`.

Just supporting a "latest" special version keyword would be great and probably not so hard as supporting nothing-at-all instead of the version number (like it currently works from top-level package pages).

I'm interested in it because it would help me a lot in adding Purescript support to http://fiatjaf.alhur.es/module-linker

(I just saw the first comment has said exactly this thing about "latest", but anyway, I'm just showing my support.)
