### ISSUE TITLE
Some kind of API for getting docstrings

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#171]
Suggested by @kritzcreek, this would be useful for psc-ide.

At the moment, `/search?q=traverse` (for example) gives you JSON if you send the appropriate Accept header, but it does not include the docstring, so it would be nice to include it.

In the same vein it might be nice to be able to serve docs as JSON, eg `/packages/purescript-foldable-traversable/0.4.2/docs/Data.Traversable#v:traverse` with a JSON Accept header would give you back something similar.

**Comment by paf31** [comment]
The `markup` field includes a HTML rendering of the docstrings now.

**Comment by hdgarrood** [comment]
Do you think this can be closed, then?

**Comment by paf31** [comment]
@kRITZCREEK Does the `markup` field work?

**Comment by kRITZCREEK** [comment]
Sry for being late on this one it seems like I overlooked it when it happened.

I think an unrendered version would be more useful. Emacs (because it has a built-in browser written in elisp) and atom can most likely deal with html but vim probably has no way to render it properly. If an editor wanted html, rendering markdown to html is trivial these days with all the libraries. It also seems a little confusing to expose a `markdown` field that contains rendered html.

**Comment by paf31** [comment]
I think the `text` field contains an unrendered version.

**Comment by kRITZCREEK** [comment]
Just tested it with postman and both fields contain html:

```
{
    "text": "<p>Create a new <code>Array</code> by applying a function to the elements of another <code>Array</code>.</p>\n",
    "markup": "<p>Create a new <code>Array</code> by applying a function to the elements of another <code>Array</code>.</p>\n",
    "url": "https://pursuit.purescript.org/packages/purescript-preface/1.1.0/docs/Array#v:map",
    "version": "1.1.0",
    "package": "purescript-preface",
    "info": {
      "typeOrValue": "Value",
      "module": "Array",
      "typeText": "forall a b. (a -> b) -> Array a -> Array b",
      "title": "map",
      "type": "declaration"
    }
  }
```

**Comment by hdgarrood** [comment]
Oops: that's a bug. My intention was that the `text` field would contain the Markdown source.
