### ISSUE TITLE
Halogen docs have disappeared

### ISSUE THREAD

**Issue by nuttycom** [purescript/pursuit#189]
This may not be quite the right place to ask about this, but it looks like the purescript-halogen docs, which I was using just a couple of days ago, have completely disappeared. Here's the missing link: https://pursuit.purescript.org/packages/purescript-halogen/0.5.14

**Comment by hdgarrood** [comment]
It's as good a place as any.

Yes, the problem is that after the re-exports changes, halogen (and batteries) are just too big and nginx is rejecting them with Request Entity Too Large. That's http status code 413, IIRC.

The fix is one or both of #188 and configuring nginx to increase the maximum permitted request body size. We just haven't gotten around to it yet.

**Comment by hdgarrood** [comment]
Sorry, that's supposed to be #186

**Comment by hdgarrood** [comment]
Fixed: https://pursuit.purescript.org/packages/purescript-halogen/0.5.18
