### ISSUE TITLE
Upload redirects to an invalid URL when Pursuit is running on the localhost

### ISSUE THREAD

**Issue by kseo** [purescript/pursuit#199]
When I clock "upload" button, the page redirects to the following URL:

http://falcon/oauth/callback?code=1fc630d67be001990f43&state=4hDVtr2w8KLL-tqbltnD87Wqz35THZLBkYHlQuHHVjlrE6mAr6lsKOmelmZkUJvPUmNNcW6uazjJk_QH

**Comment by hdgarrood** [comment]
falcon is the hostname of my laptop. I think I did it this way because GitHub won't let you set up an oauth callback url with localhost (but I'd be keen to make this easier if we can).

I think you can work around this by just replacing falcon with localhost:3000 or whatever in that url. Alternatively you could set up your own client ID and client secret on GitHub, and make a separate file alongside config/development.env containing them, to act as your dev env.

**Comment by hdgarrood** [comment]
Since we are deprecating the web upload form (#212), there's no point in addressing this now.
