### ISSUE TITLE
purescript-halogen has been missing for a few days

### ISSUE THREAD

**Issue by stefanholzmueller** [purescript/pursuit#215]
Title basically says it all. For example, this link is now broken: https://pursuit.purescript.org/packages/purescript-halogen/0.6.1/docs/Halogen.HTML.Properties#v:class_

**Comment by paf31** [comment]
This probably means the reupload script was unable to build the upload package, which probably means something isn't building correctly. If the library can be built with 0.8.5, then anyone should be able to reupload the JSON data.

**Comment by hdgarrood** [comment]
Yeah, I think it was because halogen is too large without gzipping and my script doesn't do any gzipping.

@stefanholzmueller, I've recently released a version of pulp which should make it easy for anyone to upload docs. Can you please try cloning the halogen repository, checking out the tag you want (eg v0.6.1) and then running `pulp publish --no-push`? You'll need pulp 8.2.0 at least.

**Comment by stefanholzmueller** [comment]
@hdgarrood The last time I upgraded pulp, it broke my whole setup. I do not want to risk that now, but I'll try it in a few days. Thanks for the advice though!

**Comment by hdgarrood** [comment]
Never mind, I just uploaded it.
