### ISSUE TITLE
Rewrite URLs that point to docs with no specific version to redirect to the latest version

### ISSUE THREAD

**Issue by garyb** [purescript/pursuit#277]
This would be super useful for when making links from non-pursuit documentation, as in the Halogen guide for instance.

The idea being, I could link to:

```
https://pursuit.purescript.org/packages/purescript-halogen/docs/Halogen.Query#v:action
```

Which would (currently) redirect to:

```
https://pursuit.purescript.org/packages/purescript-halogen/0.12.0/docs/Halogen.Query#v:action
```

It's not without flaws, as obviously the docs can still end up out of date, referring to dead links, but at least it avoids the overhead of having to update every link in the documentation before a new release, pointing to URLs that don't exist (yet, as updating the docs is part of the release).

**Comment by hdgarrood** [comment]
I think providing some way of linking to PureScript names in doc comments would also be nice, and might largely satisfy the use case here in a slightly better way? Perhaps we could have it so that if you write e.g. `[action](v:Halogen.Query.action)` in a doc comment, that could turn into a link that points to Halogen.Query.action, and hopefully still works when Halogen.Query is in a different module or even a different package. We already strip out relative links (at least, we do in the current Pursuit and master) so there wouldn't be any ambiguity.

**Comment by hdgarrood** [comment]
On second thoughts we'd have to be a bit careful about the colon symbol because that's how you disambiguate relative from absolute URIs. Perhaps we could define a `purescript` URI scheme for linking to PureScript things in docs: `[action](purescript:value/Halogen.Query.action)`. I think we have to say what namespace something is in, too (i.e. `value`, `type`, `kind`) because data constructors, type constructors, and kinds would otherwise be indistinguishable.

**Comment by garyb** [comment]
That wouldn't do it for the use case I'm talking about here, as this is for a collection of documentation files separate from the code entirely.

**Comment by hdgarrood** [comment]
Ah, right. Have you ever wanted that, though?

**Comment by garyb** [comment]
I want it right now, for the Halogen Guide I mentioned in the issue 😛.

**Comment by hdgarrood** [comment]
Sorry, i mean have you ever wanted to be able to link to things in inline doc comments?

**Comment by garyb** [comment]
Oh! Sure, it does sound like something that could be useful. I think I have done a few times in the past by just using `#t:Foo` relative anchors, but I can think of cases where cross-module links might have been useful too.

The namespace-with-category-discrimination looks like a good way of doing it to me too, as per your `[action](purescript:value/Halogen.Query.action)`.
