### ISSUE TITLE
purescript-pathy

### ISSUE THREAD

**Issue by icyrockcom** [purescript/pursuit#298]
https://github.com/slamdata/purescript-pathy is not on Pursuit

**Comment by hdgarrood** [comment]
This is not a pursuit issue, someone just needs to reupload the documentation (not necessarily even the author; see https://pursuit.purescript.org/help#submitting-packages).

It is unfortunate that we often have to clear the database after a major release, but before 1.0 it doesn't really seem worth the time investment to address this yet.

**Comment by icyrockcom** [comment]
Thanks for clarifying @hdgarrood - from the message:

> Package not found
> 
> No package named purescript-pathy exists in the database. If you think this is an error, please let us know by opening an issue, or visiting us on #purescript IRC on Freenode.

I gathered that "error" includes "package missing". Probably worth clarifying that for the future.

After regarding https://pursuit.purescript.org/help#submitting-packages, a few questions so I know how to do this properly going forward:

- For repositories that are not mine, I guess I just need to `git clone`, `pulp login` and `pulp publish --no-push`, correct?
- You say "not necessarily even the author". Is it an acceptable behavior across the board to publish other peoples' repositories or does it vary per organization / repository?
- If the latter, what is the accepted way of confirming that? If it's just running the above command, I guess opening an issue to say "May I upload the docs for your repository?" is just an annoyance.
- Does publishing create any additional noise (emails, github notifications, git tags, etc.) that I should be aware of / handle?

**Comment by hdgarrood** [comment]
Yes, thanks, I agree that message should be changed.

These are all great questions, by the way! I'm glad that you've prompted me to write all this down.

> For repositories that are not mine, I guess I just need to git clone, pulp login and pulp publish --no-push, correct?

Correct.

> You say "not necessarily even the author". Is it an acceptable behavior across the board to publish other peoples' repositories or does it vary per organization / repository?

I'm not sure there's an established etiquette, but generally yes. Especially if (as in this case) the library previously was on Pursuit but was lost in the chaos of a breaking compiler release. If I were the library author, I'd certainly be happy for people to publish my libraries to Pursuit if I had already pushed version tags to the repo (note that publishing requires a tag to exist and be checked out).

However, I wouldn't create a tag in a local clone of someone else's library in order to publish if if that tag didn't already exist upstream. I'd say that's definitely bad etiquette, as it would be quite awkward for the author if they wanted to use that version number later.

> If the latter, what is the accepted way of confirming that? If it's just running the above command, I guess opening an issue to say "May I upload the docs for your repository?" is just an annoyance.

I don't think there's any need to let me know you've done so or even to ask for permission, but I certainly wouldn't mind being asked or notified via a github issue.

> Does publishing create any additional noise (emails, github notifications, git tags, etc.) that I should be aware of / handle?

No, there's no additional noise like that.

**Comment by icyrockcom** [comment]
Thanks @hdgarrood - very useful! Might be worth adding this info to the help page. 

As per above, I've published and created (+closed) the above informational issue.

**Comment by hdgarrood** [comment]
> I gathered that "error" includes "package missing". Probably worth clarifying that for the future.

I have just addressed this, in #302.

**Comment by icyrockcom** [comment]
Thanks @hdgarrood!
