### ISSUE TITLE
New release needed for new Prim additions?

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#376]
The new `Prim` modules don't show up, but I'm guessing they would if we build against 0.12?

**Comment by hdgarrood** [comment]
We might need to do a little more than just building against 0.12, but yeah, I don’t think it will be difficult to display that information.

I’ve been a little hesitant because it would break existing links to things which have moved, such as RowToList. But maybe we can just not worry about that since we’re still pre-1.0.

Also I was thinking - at some point we will ideally want to be able to display documentation for multiple versions of Prim. But again, perhaps that can wait until post-1.0, so maybe we should just go ahead and do it for now.

**Comment by justinwoo** [comment]
It would be nice to push this up sometime. For now I have some generated docs pushed to https://justinwoo.github.io/generated-docs-12/generated-docs/index.html but it would be nicer to have updated Prim

**Comment by hdgarrood** [comment]
We now have an 0.7.0 release and binary, including the changes necessary to do this. The format hasn't changed or anything like that, so it should just be a case of deploying it as normal, you shouldn't need to wipe the database or anything like that.

This will break some Prim links in 0.11.x packages, e.g. if a package was published with 0.11.x and mentions one of the Prim declarations which has moved, eg `Warn`, then that link will be broken. However there's an easy fix: just reupload the package using 0.12.x. It's also unlikely that many packages will export types which mention these things anyway, I think.

**Comment by paf31** [comment]
Deployed, thanks!
