### ISSUE TITLE
Differences with haskell & searching.

### ISSUE THREAD

**Issue by losnappas** [purescript/pursuit#380]
It would be nice if searching for `mapM` yielded a result towards `traverse`. Likewise, searching for `return` -> `pure`.

And fmap, (>>), (.), etc. so people (like me) wouldn't have to dig these from wherever.

**Comment by hdgarrood** [comment]
I’m reluctant to add special cases for Haskell, just because that would introduce a maintenance burden (eg the purescript versions are unlikely to change, but if they did we’d have to make a change here as well probably). Also, if we did this, users coming from languages other than Haskell could reasonably argue that we should build in special cases for functions of those languages too, which is a route I’d rather not go down.

Remember that you can search for these functions by type if you forget what they’re called.
