### ISSUE TITLE
packages for 0.11

### ISSUE THREAD

**Issue by shmish111** [purescript/pursuit#388]
Currently I am forced to use purescript 0.11.7 as some packages aren't ready for me. I wanted to use https://pursuit.purescript.org/packages/optparse-applicative however I get
```
No package named optparse-applicative exists in the database. It might not have been published to Pursuit as of the currently active version series of the PureScript compiler (namely, 0.12.x).
```
It is very difficult to read documentation just in github, why can't pursuit show me this package, it could at least have a warning rather than remove it all together?

**Comment by shmish111** [comment]
Additionally it seems that it is using 0.12 but still doesn't appear?

**Comment by hdgarrood** [comment]
Presumably you followed that URL from google search results? It's not immediately clear to me why a broken link is showing up in search results. I suppose that package might have been published and then unpublished, perhaps due to an error with the `name` property in the manifest file. @safareli do you know what's happened here?

@safareli also, as you might have found already, you should use the `purescript-` prefix for package names so that they're easy to identify amongst non-purescript packages on the bower registry, and because some purescript build tools (such as pulp) rely on it. I'd suggest updating the bower.json's `name` property to "purescript-optparse" and republishing.

**Comment by safareli** [comment]
Yes the lib is using ps12.

You can look at the repo for now https://github.com/f-o-a-m/purescript-optparse

I just fixed `name` in bower.json (looks like i missed it before) and made a release but I got

```
0.61s$ test $TRAVIS_TAG && echo $GITHUB_TOKEN | pulp login && echo y | pulp publish --no-push
Please obtain a GitHub personal access token at:
  https://github.com/settings/tokens/new
No scopes are required, so don't check any of the boxes.
After you've done that, paste it in here: Successfully authenticated as safareli.
* ERROR: Your git working tree is dirty. Please commit or stash your changes first.
```
https://travis-ci.org/f-o-a-m/purescript-optparse/jobs/505734023#L1762

based on travis file, git tree should be fine https://github.com/f-o-a-m/purescript-optparse/blob/v0.2.1/.travis.yml do you know what can be the issue?

**Comment by hdgarrood** [comment]
I'm not sure what's causing that, but I'd recommend running `pulp publish` locally in any case.

**Comment by safareli** [comment]
executed it locally and it worked
https://pursuit.purescript.org/packages/purescript-optparse/0.2.1

**Comment by hdgarrood** [comment]
Thanks!
