### ISSUE TITLE
Upload fails when using semver ranges

### ISSUE THREAD

**Issue by garyb** [purescript/pursuit#390]
For example `2 - 3`. It may also be if you just specify a single number (e.g. `6`, which is equivalent to `^6.0.0`).

When pushing with `pulp` the result something like:

```
* Uploading documentation to Pursuit...
* Failed reading: not a valid json value
* ERROR: Expected an HTTP 201 response from Pursuit, got: 400
```

**Comment by garyb** [comment]
Update: it seems to be any version ranges actually, it also fails for things like `>=2.0.0 <4.0.0`

**Comment by hdgarrood** [comment]
I doubt that this is related to version ranges, since we don't attempt to parse them at all. The only place they're used, as far as I'm aware, is the "dependencies" list in the sidebar. See e.g. https://pursuit.purescript.org/packages/purescript-react-dom/6.1.0 which has been successfully uploaded with a `>=x.y.z <a.b.c` range.

**Comment by garyb** [comment]
I was able to publish locally so I suspect CI is using an old version of `pulp` or something; perhaps it's uploading old style manifests. False alarm! :wink:
