### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by ford-prefect** [purescript/pursuit#419]
Seems like the LetsEncrypt certificate for https://pursuit.purescript.org/ is expiring or expired (depending on whether it is currently Sep 19th for you or not).

**Comment by hdgarrood** [comment]
Thanks for the report. It’s supposed to automatically renew but I guess that hasn’t happened, I’ll take a look.

**Comment by hdgarrood** [comment]
It seems like the SSL certificate was successfully auto-renewed, it just hadn't been picked up by nginx.

**Comment by hdgarrood** [comment]
For future reference: there is a periodic cron job to reload nginx so that any renewed SSL certificates are picked up, but it hadn't been running successfully because the nginx binary is located in /usr/sbin, and for some reason /usr/sbin wasn't in the PATH when the cron job was run.

Previous crontab entry:
```
0 0 * * * nginx -s reload
```
Current crontab entry:
```
0 0 * * * (/usr/sbin/nginx -s reload && echo "$(date): reloaded nginx") >> /var/log/nginx/periodic-reloads.log 2>&1   # reload nginx in order to pick up renewed letsencrypt certificates 
```
