### ISSUE TITLE
Include repo name and url in results

### ISSUE THREAD

**Issue by natefaubion** [purescript/pursuit#6]
So its more obvious which entry to add to a bower file.

**Comment by hdgarrood** [comment]
I was thinking perhaps changing the structure of libraries.json slightly might make this easier - if we have entries in libraries.json look like this:

```
{
  "bowerName": "purescript-arrays",
  "github": { "user": "purescript", "repo": "purescript-arrays" }
}
```

then we can more easily generate a HTTPS url that's suitable for use in the pursuit UI. The current format, which uses a key called `gitUrl`, implies that a url with a different scheme would also work, like "git:"

If we do want to include a library that isn't on github, then we can extend this later so that an entry may have either a `github` key, or a `gitUrl` key (which is just passed straight to `git clone`, as happens currently).

**Comment by paf31** [comment]
I like that idea.

Also, I was thinking a lot about moving the data into a Postgres instance on the backend, maybe using something like groundhog to do the mapping. This way, we can avoid having an ever-growing JSON file, and also add new things to the schema, like examples, markdown docs, a page for each library, etc.

**Comment by hdgarrood** [comment]
Sounds good - so would libraries.json be replaced with a Haskell source file, that gets loaded into the database periodically?

**Comment by paf31** [comment]
I think we can keep `libraries.json`, it's just that during the `git clone` job, we put the data into Postgres instead of generating `data.json`.

Maybe it also makes sense to have each repo include an optional `.pursuit.json` file, with Pursuit-related metadata, like a package description in Markdown format, or links to other Pursuit packages. What do you think?

**Comment by hdgarrood** [comment]
Ahh, ok. I haven't used haskell with a relational database before, should be good :)

Would we use the data in `.pursuit.json` in the Pursuit UI?

**Comment by paf31** [comment]
Yes, that's the idea. It would be like a `.travis.yml` file, so the user wouldn't need to send a PR to update their library's page. But adding or removing a library would still require a PR.

**Comment by hdgarrood** [comment]
Is there a benefit to doing it that way over just linking to a github repository from Pursuit? I would expect people to put that kind of information in their project's README.
