### ISSUE TITLE
Issue compiling pursuit-2 branch

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#86]
```text
src/Settings/StaticFiles.hs:1:1:
    Exception when trying to run compile-time code:
      when expecting a Text, encountered Null instead
    Code: staticFiles (appStaticDir compileTimeAppSettings)
```

Is this a Yesod config issue? I'm not used to building Yesod apps.

**Comment by hdgarrood** [comment]
Yes, I think this is because there's no github oauth client ID or client secret configured. I've been using `cabal configure -fdev`, which defines DEVELOPMENT for cpp, and then there are default values set for these, see https://github.com/purescript/pursuit/blob/pursuit-2/src/Settings.hs#L87-L96

Settings.hs and Settings/StaticFiles.hs are mostly unchanged from what the scaffolding generator produced. I am becoming tempted to rewrite them so that error messages are somewhat scrutable, and potentially to get rid of the yaml files as well.
