### ISSUE TITLE
Deploy Pursuit 2 to purescript.org

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#87]
@hdgarrood Let's list the things that are involved here, and check them off as they're completed:

- [x] Generate Hoogle files (seems this is done)
- [x] Integrate Hoogle as a library (is this still the plan?)
  - [x] Query API
  - [x] Inserting records for a new library
- [x] Configure `nginx` (@paf31)
- [x] Insert docs for new core libraries

What else?

Please let me know if there's anything you need from me.

**Comment by hdgarrood** [comment]
Sorry, I thought I'd already replied to this (it seems email replies aren't working for me).

Are we aiming for a "minimum viable product" with this checklist? If so, I think it's just:

- [ ] make error pages nicer
- [ ] come up with and implement a strategy for backing everything up

The original plan for backups (chuck everything in a git repository and put it on github) still seems like a good option. Do you think a bash script and cron job would work for that?

Also I thought we were going to try to have a Hoogle instance running separately, so that they can be upgraded independently? Anyway I don't think we should worry about that too much right now, we can deal with it after Hoogle supports PureScript code, I think.

**Comment by paf31** [comment]
Yep, I think "MVP then iterate" is the best way to go here.

For backups, I'm happy to set something up using cron as a first pass, and we can come back to it, once we have things working.

**Comment by hdgarrood** [comment]
:+1: perhaps I can also put together a script or something to deploy all the core libraries in one go.
