### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#88]
Using something like Disqus on each package/module page perhaps?

I think it would be nice to encourage users to discuss and document library functionality on Pursuit, and this seems like an easy way to tie a discussion to a particular module or package.

**Comment by hdgarrood** [comment]
:+1:

**Comment by hdgarrood** [comment]
On second thoughts, I'm not so sure about this. I think it would be quite hard to make sure that the right people saw comments on a package (that is, the package's maintainers). I also think there's a risk of confusion from out-of-date comments; if someone asks about a function which is later removed, for example, I'm not aware of a good way of stopping that comment from appearing.

For questions regarding an API (eg "how do I use this"), I think github issues, or perhaps google groups or SO is usually a better fit. For suggesting improvements, I think it's better to open issues and get the documentation itself clarified or fixed, rather than having an extra section at the bottom (which people might miss if the thing they're interested in is at the top of the page, and which isn't nearly as trustworthy as the actual documentation).

The Ruby documentation does use Disqus on each module page, and I don't think it works very well there. For example: http://ruby-doc.org/stdlib-2.1.1/libdoc/net/http/rdoc/Net/HTTP.html - I think all of this discussion would have been better off in github issues.
