### ISSUE TITLE
Upload JSON file from psc-publish

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#92]
`psc-publish` should perform the upload to Pursuit and show the link to the verification URL.

This is probably lower priority than #90 and #89.

**Comment by hdgarrood** [comment]
I think I'd rather modify `psc-publish` so that it can do the upload.

**Comment by paf31** [comment]
Yep, that works. The only reason I prefer a page is that it will do the redirect to the verification page.

Maybe if there's time, we can support both, like Hackage does with `cabal upload`.

**Comment by hdgarrood** [comment]
If `psc-publish` were doing the upload, I would have it print the verification page URL so that you can go straight there, though.

Re multiple uploading methods: unless there's a good reason why some users would prefer one and other users would prefer the other, I think I'd rather stick to one way of uploading packages; otherwise, we'll be forcing people to decide which one to use, which just seems like unnecessary extra effort, particularly for first-time uploaders.

Come to think of it, perhaps that reason could be that not all OSes make it easy to open a URL in a web browser from a terminal window. It is easy on Ubuntu, if you're using the default terminal. Last I checked, it's a bit awkward on Windows. How is it on OS X?

**Comment by paf31** [comment]
In `Terminal.app`, you can right click and say `Open URL`. 

I'm totally fine with having `psc-release` link to the verification page then. Let's try and keep the dependencies light though, if we can.

I'll update the title of the issue.

**Comment by hdgarrood** [comment]
The lightest option wrt dependencies seems to be `http-streams`, which would add the following:

* base64-bytestring
* bytestring-builder
* case-insensitive
* http-common
* http-streams
* io-streams
* network
* network-uri
* openssl-streams
* zlib
* zlib-bindings
* HsOpenSSL

(HTTP is lighter - it would only add HTTP, network, network-uri, and old-time. However, it doesn't support HTTPS, so that would be irritating if we started using HTTPS.)

What do you think?

**Comment by paf31** [comment]
Hmm. Does `HsOpenSSL` work on Windows, I've not tested it?

This is the other reason I'd prefer to use an upload page, honestly: this is a fairly heavy set of dependencies compared to the current set.

We should do the "right thing" though, and if that's an upload command line tool, then we need to either use HTTP or `http-streams`. Is there an option which uses `tls`?

**Comment by hdgarrood** [comment]
Nor have I. The changelog does at least indicate that they support windows, but it does seem like it could make it quite difficult to get the thing to compile. Perhaps an upload page is more sensible, then.

**Comment by hdgarrood** [comment]
`wreq` and `http-conduit` use `tls` (via `http-client-tls`) but they both add a lot of dependencies, more than `http-streams`.

**Comment by paf31** [comment]
How about we make a proof of concept with whatever library you're most comfortable with first, and then assess the potential damage later?

**Comment by hdgarrood** [comment]
Quotes from IRC, for the sake of anyone reading this later:

> 23:09 \<hdgarrood\> i've changed my mind, i think having an upload page like you suggested as the default upload method is more sensible
> 23:09 \<hdgarrood\> this way we can get rid of the uploaded/ directory and all of the verification code, and I think that whole mechanism (especially keeping up to 100 on disk, deleting the oldest every time a new one comes in) is one of the areas of the code which is most likely to cause problems
> 23:11 \<paf31\> hdgarrood: interesting, why?
> 23:11 \<paf31\> the library hassle?
> 23:12 \<hdgarrood\> then the verification page just becomes a confirmation page, really, since we will already have made them log in by that stage
> 23:13 \<hdgarrood\> and for users that want to, we could maybe create a command line tool which you can give your github token to in order to log in, and then you can upload packages without even having to open a browser
> 23:15 \<hdgarrood\> the issue of extra dependencies influenced this a little bit but the other stuff I just said has more to do with it
>

**Comment by hdgarrood** [comment]
Fixed by 2f448c7 (and a few others)
