### ISSUE TITLE
Upload packages directly inside the Pursuit web app

### ISSUE THREAD

**Issue by michaelficarra** [purescript/pursuit#96]
If I have a public repo on github, and I've published it to bower, my ideal workflow would be selecting the repo from a list (you can already read my public repos on github after authing) and having the pursuit server generate the pursuit.json file for me. Are there technical restrictions that make this impossible?

**Comment by hdgarrood** [comment]
I agree, that does sound like a much nicer UI. It didn't occur to me to do it like that.

The only thing that makes this difficult is that `psc-publish` uses the output of `bower list --json --offline` (that is, the currently installed versions of things on the author's machine) in order to decide what versions of dependencies to link to. If package A exports something that refers to a type in package B (eg: [Data.Array.some](http://new-pursuit.purescript.org/packages/purescript-arrays/0.4.0/docs/Data.Array#d:some) refers to Lazy and Alternative) then we want those to become links in pursuit, and we want to ensure we link to a version of B which builds with A. I didn't want to come up with a way of automatically selecting resolutions in a case where bower complains about unresolvable dependencies; leaving it to the author to make these decisions seems more sensible.

(aside: the bug that led to Lazy and Alternative not displaying links has been fixed, we just need to regenerate the data :)

**Comment by michaelficarra** [comment]
If the dependencies don't auto-resolve, make them upload the file themselves. But for the majority of cases, they should resolve fine, and there will be no human interaction necessary.

**Comment by hdgarrood** [comment]
Sounds good.

**Comment by paf31** [comment]
Another option might be to provide an endpoint so that updates could be pushed from Travis after a release build?

**Comment by hdgarrood** [comment]
So Travis would run `psc-publish`, and fail if dependencies don't resolve?

**Comment by paf31** [comment]
I'm just thinking that if the build is successful, Travis already has all of the dependencies there, in the right place, ready to process.

We would probably keep the current approach too, in case people don't use Travis.

**Comment by hdgarrood** [comment]
Ahh, right. Yep, sounds good. Can we get the github api key if it has been encrypted in .travis.yml? (for authentication to pursuit)

**Comment by michaelficarra** [comment]
Let's do both. Can we track these as separate feature requests?

**Comment by michaelficarra** [comment]
@hdgarrood You accidentally closed this instead of #99 in #112. Please re-open this and close #99.

**Comment by hdgarrood** [comment]
Cheers, I didn't notice that.

**Comment by hdgarrood** [comment]
There are a few requirements for `psc-publish` to be able to generate the data for a package, and I think we should have a mechanism to check that these requirements are satisfied *before* a package author pushes a tag; we don't want to have people push a tag, then have to delete it and retag after, say, learning that they need to add a "repository" field to their bower.json file, and so on.

We could add a flag to `psc-publish` for this, perhaps `psc-publish --check`. It could be the same as the normal mode, except that doesn't produce any output, and it doesn't require the currently checked out commit to be tagged with a version. It could also check that dependencies can be resolved without messing up the current directory, by creating a temporary directory and doing all the work in there.

Second, perhaps we could encourage people to run this as part of their build process? The standard command could be `pulp build && pulp test && psc-publish --check`.

Alternatively, perhaps we could change `psc-publish` so that you can give it the version as an argument perhaps, rather than taking it from the git repository in the current directory. Then we could have a separate tool which calls `psc-publish` to attempt to generate the JSON first, and then bumps your version in bower.json and tags it for you only if `psc-publish` succeeded.

**Comment by hdgarrood** [comment]
Thinking about this a little more. I think the problem here is "it's annoying to have to do a bunch of extra stuff every time I want to do a release," right?

If so, I think we can solve it better by having a single tool which takes care of all the pursuit stuff for you as well as tagging and pushing. So: https://github.com/bodil/pulp/issues/57
